[nginx]
nginx-1 ansible_host=192.168.122.7 ansible_user=ubuntu
nginx-2 ansible_host=192.168.122.214 ansible_user=ubuntu

[backend]
backend-1 ansible_host=192.168.122.238 ansible_user=ubuntu
backend-2 ansible_host=192.168.122.75 ansible_user=ubuntu

[db]
db-1 ansible_host=192.168.122.189 ansible_user=ubuntu

[iscsi]
iscsi-target ansible_host=192.168.122.111 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
